version: '3.1'

services:

  app:
    container_name: hse_piman_app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - '4202:4200'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge